name: CI

on:
  push:
    branches: [ main ]
  
jobs:
  test-fsharp:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore

    - name: Install Fantomas
      run: dotnet tool install fantomas --global

    - name: Check formatting
      run: fantomas --check .
      
    - name: Build
      run: dotnet build --no-restore -warnaserror
      
    - name: Test
      run: dotnet test tests/Tests.fsproj
      
    - name: Run main program
      run: dotnet run --no-build --project lab.fsproj
  
  test-python:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10]

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
    
    - name: Run tests
      run: |
        pytest test_problems.py -v
    